
 oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
                                  ---  PhyML 20120412  ---                                             
                            http://www.atgc-montpellier.fr/phyml                                          
                         Copyright CNRS - Universite Montpellier II                                 
 oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

. Sequence filename: 			O59828_ALR1_SCHPO.alg.clean
. Data set: 				#1
. Tree topology: 			fixed
. Initial tree: 			BioNJ
. Model of amino acids substitution: 	MtREV
. Number of taxa: 			151
. Log-likelihood: 			-96450.37582
. Unconstrained likelihood: 		-2586.31862
. Parsimony: 				21744
. Tree size: 				118.42663
. Discrete gamma model: 		Yes
  - Number of categories: 		4
  - Gamma shape parameter: 		0.993
. Proportion of invariant: 		0.037

. Run ID:				none
. Random seed:				1437040839
. Subtree patterns aliasing:		no
. Version:				20120412
. Time used:				0h2m3s (123 seconds)

 oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
 Suggested citations:
 S. Guindon, JF. Dufayard, V. Lefort, M. Anisimova, W. Hordijk, O. Gascuel
 "New algorithms and methods to estimate maximum-likelihood phylogenies: assessing the performance of PhyML 3.0."
 Systematic Biology. 2010. 59(3):307-321.

 S. Guindon & O. Gascuel
 "A simple, fast, and accurate algorithm to estimate large phylogenies by maximum likelihood"
 Systematic Biology. 2003. 52(5):696-704.
 oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
